### ISSUE TITLE
Detailed Antibiotics Breakdown

### ISSUE THREAD

**Issue by DerekRoberts** [HDCbc/queries#33]
Break down HDC-1997 or create similar query that shows antibiotic prescription % by category: 

   -Macrolides
J01F MACROLIDES, LINCOSAMIDES AND STREPTOGRAMINS

J01FA09                clarithromycin

J01FA10                azithromycin

J01FA01                erythromycin

J01FF01                clindamycin

   -Penicillins
J01C BETA-LACTAM ANTIBACTERIALS, PENICILLINS

J01CF02                cloxacillin

J01CA01               ampicillin

J01CA04               amoxicillin

   -Quinolones
J01M QUINOLONE ANTIBACTERIALS

J01MA12              levofloxacin       

J01MA14              moxifloxacin

J01MA02              ciprofloxacin

   -Tetracyclines
J01A TETRACYCLINES

J01AA02               doxycycline

J01AA07               tetracycline

J01AA08               minocycline

   -Sulphonamides
J01E SULFONAMIDES AND TRIMETHOPRIM

J01EE01                sulfamethoxazole and trimethoprim

   -Nitrofurans
J01XE Nitrofuran derivatives

J01XE01                nitrofurantoin

   -1st Gen Cephalosporins.
CEPHALOSPORINS

J01DB First-generation cephalosporins

J01DB01               cefalexin

   -2nd Gen Cephalosporins.
J01DC Second-generation cephalosporins

J01DC02               cefuroxime                   

J01DC04               cefaclor

   -3rd Gen Cephalosporins.
J01DD Third-generation cephalosporins

J01DD08               cefixime

**Comment by WooferM** [comment]
Create 19 new queries, one for each antibiotic. 

The denominator will be the total number of prescriptions in the last year that match any of the specific antibiotic codes. The numerator will be the total number of prescriptions in the last year that match the single antibiotic code for the query.

Combining the results of the individual queries into categories will be done in the HDC application.
